steps:

  - wait

  - trigger: "eosio-dot-contracts-base-images-beta"
    label: ":docker: Ensure Base Images"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - wait

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - ./.cicd/build.sh
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18

  - wait

  - label: ":ubuntu: Ubuntu 18.04 - Test"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' && tar -xzf build.tar.gz"
      - ./.cicd/test.sh
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18