steps:
  - wait

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command: |
      ./.cicd/build.sh
      tar -pczf build.tar.gz build
      buildkite-agent artifact upload build.tar.gz
    agents:
      queue: "automation-eks-eos-builder-beta-fleet"
    timeout: "${TIMEOUT:-60}"
    skip: "$SKIP_UBUNTU_18"

  - wait

  - label: ":ubuntu: Ubuntu 18.04 - Test"
    command: |
      buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build'
      tar -xzf build.tar.gz
      ./.cicd/test.sh
    agents:
      queue: "automation-eks-eos-tester-beta-fleet"
    timeout: "${TIMEOUT:-10}"
    skip: "$SKIP_UBUNTU_18"

  - wait:
    continue_on_failure: true

  - label: ":bar_chart: Test Metrics"
    command: |
      echo '+++ :compression: Extracting Test Metrics Code'
      tar -zxf .cicd/metrics/test-metrics.tar.gz
      echo '+++ :javascript: Running test-metrics.js'
      node --max-old-space-size=32768 test-metrics.js
    agents:
      queue: "automation-eks-eos-tester-beta-fleet"
    timeout: 10
    soft_fail: true
